on: [push]

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv lock

  linting:
    runs-on: ubuntu-latest
    needs: lock
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff check .

  formatting:
    runs-on: ubuntu-latest
    needs: lock
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uvx ruff format --check .

  type-check:
    runs-on: ubuntu-latest
    needs: lock
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run pyright .

  build:
    runs-on: ubuntu-latest
    needs: [lock, linting, formatting, type-check]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: uv run pyinstaller ./NetworkStreamTool.py
      - run: cp ./.to_add_to_internal/* ./dist/NetworkStreamTool/_internal/
