on: push

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Sync dependencies
        run: uv sync

      - name: Cache virtual environment
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-uv-venv
          path: ./.venv

  linting:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore virtual environment
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-uv-venv
          path: ./.venv

      - run: uvx ruff check .

  formatting:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore virtual environment
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-uv-venv
          path: ./.venv

      - run: uvx ruff format --check .

  type-check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore virtual environment
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-uv-venv
          path: ./.venv

      - run: uv run pyright .

  build:
    runs-on: ubuntu-latest
    needs: [setup, linting, formatting, type-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore virtual environment
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-uv-venv
          path: ./.venv

      - run: uv run pyinstaller ./NetworkStreamTool.spec
      - run: cp -r ./.to_add_to_internal/* ./dist/NetworkStreamTool/_internal/
